CREATE DATABASE IF NOT EXISTS escola CHARACTER SET utf8mb4 COLLATE utf8mb4_USE escola;
CREAT TABLE IF NOT EXISTS alunos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR (100) NOT NULL,
    idade INT NOT NULL;
    email VARCHAR (120) NOT NULL,
    criado_em TIMESTAMP DEFAUT CURRENT_TIMESTAMP
);